version: '3.3'

services:
  server:
    build:
      # default pytorch
      # dockerfile: ./Dockerfile
      # transformer enngine 
      dockerfile: ./Dockerfile_te
      context: . 
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
    - ./:/code
    cap_add:
      - ALL
    # network_mode: "host"