# transformer engine 
# FROM nvcr.io/nvidia/pytorch:25.03-py3
FROM nvcr.io/nvidia/pytorch:25.06-py3
ARG DEBIAN_FRONTEND=noninteractive
# https://github.com/docker/build-push-action/issues/933#issuecomment-1687372123
# RUN rm /etc/apt/sources.list.d/cuda*.list
RUN apt-get update --fix-missing && apt-get upgrade -y && apt-get install ffmpeg libsm6 libxext6 ncdu -y
RUN apt-get install git curl numactl wget unzip iproute2 htop git-lfs -y && pip install nvitop 

# этот пользователь уже внутри данного контейнера, у него UID 1000
ARG USERNAME=ubuntu
# ARG USER_UID=1000
# ARG USER_GID=$USER_UID

# Create the user
RUN apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

# # ********************************************************
# # * Anything else you want to do like clean up goes here *
# # ********************************************************

# # [Optional] Set the default user. Omit if you want to keep the default as root.
USER $USERNAME
RUN  echo -e "\nexport PATH=$PATH:/home/ubuntu/.local/bin\n" >>  /home/ubuntu/.bashrc 
# # RUN sudo chown -R $USERNAME /opt/conda
# # RUN conda init
WORKDIR /code
# apt-get update && apt-get install ffmpeg libsm6 libxext6  -y