model_name_or_path: unsloth/Llama-3.2-1B-Instruct 
per_device_train_batch_size: 4 
per_device_eval_batch_size: 32 
do_train: true
do_eval: true
output_dir: ./hf_trainer_edu 
report_to: wandb 
block_size: 2048 
logging_steps: 4 
eval_steps: 500 
eval_strategy: steps 
include_num_input_tokens_seen: 
attn_implementation: flash_attention_2 
optimization_level: opt_1 
bf16: true
remove_unused_columns: False 
gradient_checkpointing: False 
num_train_epochs: 1
save_steps: 5000000 
data_seed: 42 
optim: adamw_torch 
lr_scheduler_type: warmup_stable_decay 
warmup_steps: 1000
dataloader_type: mosaic_edu 
max_steps: 5000
# eval_on_start: true
# dataloader_type hf_edu \
# dataloader_type ram_edu
# dataloader_type hf