model_name_or_path: unsloth/Llama-3.2-1B-Instruct 
# per_device_train_batch_size: 4 
# per_device_train_batch_size: 8 
# per_device_train_batch_size: 10 # max for A100-40GB
per_device_train_batch_size: 12 # max for A100-40GB with liger
per_device_eval_batch_size: 32 
do_train: true
do_eval: true
output_dir: ./model_checkpoints/1B_llama_3_2 
report_to: wandb 
block_size: 2048 
logging_steps: 4
save_total_limit: 1
eval_strategy: steps 
include_num_input_tokens_seen: true
# optimization_level: opt_1 # baseline hf model
optimization_level: opt_2 # liger kernel
# optimization_level: opt_3 # cut cross entropy+torch.compile
bf16: true
remove_unused_columns: False 
gradient_checkpointing: False 
data_seed: 42 
optim: adamw_torch 
lr_scheduler_type: warmup_stable_decay 
warmup_steps: 1000
dataloader_type: mosaic_edu
dataloader_num_workers: 4
# save_tokens: 10_000_000
save_tokens: 500_000_000
# max_train_tokens: 405_635_072
max_train_tokens: 10_000_000_000
eval_on_start: true